# Generated by Django 5.0.7 on 2024-07-31 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy', '0003_doctor_patient_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Patient'), (2, 'Doctor')], null=True),
        ),
    ]
