# Generated by Django 5.0.7 on 2024-07-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy', '0007_alter_customuser_managers_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
